agent {
    data_dir = "/run/spire"
    log_level = "DEBUG"
    server_address = "spire-server"
    server_port = "8081"
    socket_path = "/opt/spire/sockets/agent.sock"
    trust_domain = "example.org"
    insecure_bootstrap = true
}

plugins {
    NodeAttestor "x509pop" {
        plugin_data {
            private_key_path = "/opt/spire/certs/agent.key.pem"
            certificate_path = "/opt/spire/certs/agent.crt.pem"
        }
    }

    KeyManager "memory" {
        plugin_data {
        }
    }

    WorkloadAttestor "docker" {
        plugin_data {
           docker_socket_path = "unix:///var/run/docker.sock"
        }
    }
}
